# Generated by Django 4.1.7 on 2023-02-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_user_delete_userregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="IHA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("weight", models.FloatField()),
                ("category", models.CharField(max_length=50)),
            ],
        ),
    ]
