# Generated by Django 4.1.7 on 2023-02-22 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0004_iha"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IHA",
        ),
    ]
